In [21]:
import sqlite3
import pandas as pd

dbConn = sqlite3.connect('nfl_data.db')
dbCursor = dbConn.cursor()
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

# roster = pd.read_csv('server/nfl-big-data-bowl-2021/roster_2018.csv', low_memory = False)
# roster.to_sql('roster2018', dbConn, if_exists='replace', index = False)

# pbp = pd.read_csv('server/nfl-big-data-bowl-2021/pbp2018.csv', low_memory = False)
# pbp.to_sql('pbp', dbConn, if_exists='replace', index = False)

# games = pd.read_csv('server/nfl-big-data-bowl-2021/games.csv', low_memory = False)
# games.to_sql('games', dbConn, if_exists='replace', index = False)

# players = pd.read_csv('server/nfl-big-data-bowl-2021/players.csv', low_memory = False)
# players.to_sql('players', dbConn, if_exists='replace', index = False)

# plays = pd.read_csv('server/nfl-big-data-bowl-2021/plays.csv', low_memory = False)
# plays.to_sql('plays', dbConn, if_exists='replace', index = False)

# i = 1
# while i < 18:
#     file = "week" + str(i)
#     fileName = "server/nfl-big-data-bowl-2021/" + file + ".csv"
#     week = pd.read_csv(fileName, low_memory = False)
#     week.to_sql(file, dbConn, if_exists='replace', index = False)
#     i += 1

query = """
SELECT *
FROM week1
LIMIT 5;
"""

dbCursor.execute(query)
df = pd.DataFrame(dbCursor.fetchall())
df.head(len(df))

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,2018-09-07T01:07:14.599Z,91.73,26.67,0.00,0.01,0.02,289.57,240.93,None,310.0,Matt Ryan,2.0,QB,1,away,2018090600,75,left,None
1,2018-09-07T01:07:14.599Z,88.89,36.47,0.01,0.01,0.01,105.63,66.66,None,79848.0,Malcolm Jenkins,27.0,SS,1,home,2018090600,75,left,None
2,2018-09-07T01:07:14.599Z,91.35,44.16,0.02,0.03,0.01,290.45,16.86,None,2495454.0,Julio Jones,11.0,WR,1,away,2018090600,75,left,HITCH
3,2018-09-07T01:07:14.599Z,86.31,22.01,0.09,0.42,0.01,70.12,168.91,None,2495613.0,Corey Graham,24.0,FS,1,home,2018090600,75,left,None
4,2018-09-07T01:07:14.599Z,90.78,36.15,0.00,0.00,0.00,257.61,193.97,None,2533040.0,Mohamed Sanu,12.0,WR,1,away,2018090600,75,left,HITCH

In [6]:
query = """
        SELECT full_name, route
        FROM pbp
        JOIN roster2018 ON pbp.receiver_player_id = roster2018.gsis_id
        JOIN week1 on pbp.play_id = week1.playId
        WHERE complete_pass = 1 AND pbp.week <= 17
        LIMIT 5;
        """

dbCursor.execute(query)
df = pd.DataFrame(dbCursor.fetchall())
df.head(len(df))

NameError: name 'dbCursor' is not defined